const AuthTypes = {
  LOGIN_REQUEST: "AUTH_LOGIN_REQUEST",
  LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  SIGNUP_REQUEST: "AUTH_SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "AUTH_SIGNUP_SUCCESS",
  SIGNUP_FAILED: "AUTH_SIGNUP_FAILED",
  LOGOUT: "AUTH_LOGOUT",
};

const ProfileTypes = {
  GET_ACCOUNT_REQUEST: "PROFILE_GET_ACCOUNT_REQUEST",
  GET_ACCOUNT_SUCCESS: "PROFILE_GET_ACCOUNT_SUCCESS",
  UPDATE_ACCOUNT_REQUEST: "PROFILE_UPDATE_ACCOUNT_REQUEST",
  UPDATE_ACCOUNT_SUCCESS: "PROFILE_UPDATE_ACCOUNT_SUCCESS",
};

export { AuthTypes,ProfileTypes };
